import { FormEvent, useEffect, useState } from "react";
import AdminGuard from "../../../components/admin/AdminGuard";
import AdminLayout from "../../../components/admin/AdminLayout";
import ImageUpload from "../../../components/admin/ImageUpload";
import { deleteAdminBanner, listAdminBanners, saveAdminBanner } from "../../../lib/content/client";
import type { HomeBanner } from "../../../lib/content/types";
const empty: Partial<HomeBanner> = { title: "", subtitle: "", image_url: "", mobile_image_url: "", button_text: "", button_url: "", overlay_strength: 0.35, active: true, display_order: 0, starts_at: null, ends_at: null };
const AdminBanners = () => {
  const [items, setItems] = useState<HomeBanner[]>([]); const [value, setValue] = useState<Partial<HomeBanner>>(empty); const [error, setError] = useState<string | null>(null);
  const load = async () => setItems(await listAdminBanners());
  useEffect(() => { void load().catch(() => setError("Não foi possível carregar banners.")); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); setError(null); try { await saveAdminBanner(value); setValue(empty); await load(); } catch { setError("Não foi possível salvar o banner."); } };
  return <AdminGuard><AdminLayout title="Banners da home"><div className="grid gap-6 xl:grid-cols-[420px_1fr]"><form className="space-y-4 rounded-xl border bg-white p-5" onSubmit={submit}><h2 className="font-semibold">{value.id ? "Editar banner" : "Novo banner"}</h2>{(["title","subtitle","button_text","button_url"] as const).map((key) => <label className="block text-sm" key={key}>{key.replace("_"," ")}<input className="mt-1 w-full rounded border px-3 py-2" onChange={(e) => setValue({ ...value, [key]: e.target.value })} value={(value[key] as string) ?? ""} /></label>)}<label className="block text-sm">Imagem desktop<ImageUpload bucket="site-assets" onChange={(url) => setValue({ ...value, image_url: url })} value={value.image_url} /></label><label className="block text-sm">Imagem mobile<ImageUpload bucket="site-assets" onChange={(url) => setValue({ ...value, mobile_image_url: url })} value={value.mobile_image_url} /></label><div className="grid grid-cols-2 gap-3"><label className="text-sm">Início<input className="mt-1 w-full rounded border px-3 py-2" onChange={(e) => setValue({ ...value, starts_at: e.target.value ? new Date(e.target.value).toISOString() : null })} type="datetime-local" /></label><label className="text-sm">Fim<input className="mt-1 w-full rounded border px-3 py-2" onChange={(e) => setValue({ ...value, ends_at: e.target.value ? new Date(e.target.value).toISOString() : null })} type="datetime-local" /></label><label className="text-sm">Ordem<input className="mt-1 w-full rounded border px-3 py-2" onChange={(e) => setValue({ ...value, display_order: Number(e.target.value) })} type="number" value={value.display_order ?? 0} /></label><label className="text-sm">Overlay<input className="mt-1 w-full rounded border px-3 py-2" max="1" min="0" onChange={(e) => setValue({ ...value, overlay_strength: Number(e.target.value) })} step=".05" type="number" value={value.overlay_strength ?? .35} /></label></div><label className="flex gap-2 text-sm"><input checked={value.active ?? true} onChange={(e) => setValue({ ...value, active: e.target.checked })} type="checkbox" />Ativo</label>{error && <p className="text-sm text-red-600">{error}</p>}<button className="rounded bg-orange-500 px-4 py-2 font-semibold text-white">Salvar</button></form><div className="space-y-3">{items.map((item) => <article className="flex items-center justify-between rounded-xl border bg-white p-4" key={item.id}><div><h3 className="font-semibold">{item.title || "Sem título"}</h3><p className="text-sm text-gray-500">Ordem {item.display_order} · {item.active ? "Ativo" : "Inativo"}</p></div><div><button className="text-orange-600" onClick={() => setValue(item)}>Editar</button><button className="ml-4 text-red-600" onClick={() => void deleteAdminBanner(item.id).then(load)}>Excluir</button></div></article>)}</div></div></AdminLayout></AdminGuard>;
};
export default AdminBanners;
