import { FormEvent, useEffect, useState } from "react";
import AdminGuard from "../../../components/admin/AdminGuard";
import AdminLayout from "../../../components/admin/AdminLayout";
import ConfirmButton from "../../../components/admin/ConfirmButton";
import { deleteAdminHomeSection, listAdminHomeSections, saveAdminHomeSection } from "../../../lib/content/client";
import type { HomeSection } from "../../../lib/content/types";
const empty: Partial<HomeSection> & { section_key: string } = { section_key: "featured_products", title: "", subtitle: "", content: {}, active: true, display_order: 0 };
const AdminSections = () => {
  const [items,setItems]=useState<HomeSection[]>([]); const [value,setValue]=useState(empty); const [json,setJson]=useState("{}"); const [error,setError]=useState<string|null>(null);
  const load=async()=>setItems(await listAdminHomeSections()); useEffect(()=>{void load()},[]);
  const submit=async(e:FormEvent)=>{e.preventDefault();try{await saveAdminHomeSection({...value,content:JSON.parse(json)});setValue(empty);setJson("{}");await load()}catch{setError("Confira o JSON e os campos informados.")}};
  return <AdminGuard><AdminLayout title="Seções da home" description="Use tipos predefinidos e conteúdo JSON estruturado."><div className="grid gap-6 xl:grid-cols-[420px_1fr]"><form className="space-y-4 rounded-xl border bg-white p-5" onSubmit={submit}><label className="block text-sm">Tipo<select className="mt-1 w-full rounded border px-3 py-2" onChange={e=>setValue({...value,section_key:e.target.value})} value={value.section_key}>{["featured_products","destinations","categories","promotional_banner","benefits","testimonials","latest_blog_posts","newsletter","custom_content"].map(k=><option key={k}>{k}</option>)}</select></label><label className="block text-sm">Título<input className="mt-1 w-full rounded border px-3 py-2" onChange={e=>setValue({...value,title:e.target.value})} value={value.title??""}/></label><label className="block text-sm">Subtítulo<input className="mt-1 w-full rounded border px-3 py-2" onChange={e=>setValue({...value,subtitle:e.target.value})} value={value.subtitle??""}/></label><label className="block text-sm">Conteúdo JSON<textarea className="mt-1 min-h-[180px] w-full rounded border p-3 font-mono text-xs" onChange={e=>setJson(e.target.value)} value={json}/></label><label className="block text-sm">Ordem<input className="mt-1 w-full rounded border px-3 py-2" onChange={e=>setValue({...value,display_order:Number(e.target.value)})} type="number" value={value.display_order??0}/></label><label className="flex gap-2"><input checked={value.active??true} onChange={e=>setValue({...value,active:e.target.checked})} type="checkbox"/>Ativa</label>{error&&<p className="text-sm text-red-600">{error}</p>}<button className="rounded bg-orange-500 px-4 py-2 text-white">Salvar</button></form><div className="space-y-3">{items.map(item=><article className="flex justify-between rounded-xl border bg-white p-4" key={item.id}><div><h3 className="font-semibold">{item.title||item.section_key}</h3><p className="text-sm text-gray-500">{item.section_key} · ordem {item.display_order} · {item.active?"ativa":"inativa"}</p></div><div><button className="text-orange-600" onClick={()=>{setValue(item);setJson(JSON.stringify(item.content,null,2))}}>Editar</button><ConfirmButton className="ml-4 text-red-600 hover:text-red-700" confirmLabel="Excluir seção" message={`Excluir a seção "${item.title||item.section_key}"? Esta ação não pode ser desfeita.`} onConfirm={()=>deleteAdminHomeSection(item.id)} onDone={load}>Excluir</ConfirmButton></div></article>)}</div></div></AdminLayout></AdminGuard>;
};
export default AdminSections;
