import { FormEvent, ReactNode, useEffect, useState } from "react";
import { listAdminProducts } from "../../lib/admin/client";
import { listAdminBanners, listAdminHomeSections, saveAdminBanner, saveAdminHomeSection } from "../../lib/content/client";
import type { HomeBanner, HomeSection } from "../../lib/content/types";
import type { Product } from "../../lib/products/types";

const keys = ["featured_products","destinations","benefits","testimonials","promotional_banner","latest_blog_posts","newsletter"] as const;
type Key = typeof keys[number];
const labels: Record<Key,string> = {featured_products:"Produtos em destaque",destinations:"Destinos",benefits:"Benefícios",testimonials:"Depoimentos",promotional_banner:"Chamada promocional",latest_blog_posts:"Blog na home",newsletter:"Newsletter"};
const defaults: Record<Key,any> = {
  featured_products:{title:"Pacotes em destaque",subtitle:"Experiências selecionadas para sua próxima viagem.",content:{product_ids:[],limit:6},active:true},
  destinations:{title:"Destinos mais procurados",subtitle:"Inspire-se para sua próxima viagem.",content:{items:[]},active:true},
  benefits:{title:"Viaje com tranquilidade",subtitle:"",content:{items:[]},active:true},
  testimonials:{title:"Quem viaja com a RW Turismo recomenda",subtitle:"",content:{items:[]},active:false},
  promotional_banner:{title:"Pronto para sua próxima viagem?",subtitle:"",content:{text:"",button_text:"",button_url:""},active:false},
  latest_blog_posts:{title:"Conteúdos para inspirar sua viagem",subtitle:"",content:{},active:false},
  newsletter:{title:"Receba ofertas e novidades",subtitle:"",content:{},active:false},
};
const placeholders: Key[] = ["latest_blog_posts","newsletter"];
const cls="mt-1 w-full rounded-lg border px-3 py-2";
const emptyBanner:Partial<HomeBanner>={title:"",subtitle:"",image_url:"",mobile_image_url:"",button_text:"",button_url:"",overlay_strength:.35,active:true,display_order:0};

const HomeEditor=()=>{
  const [sections,setSections]=useState<HomeSection[]>([]),[banner,setBanner]=useState<Partial<HomeBanner>>(emptyBanner),[products,setProducts]=useState<Product[]>([]);
  const [message,setMessage]=useState<Record<string,string>>({}),[busy,setBusy]=useState<string|null>("load");
  const load=async()=>{setBusy("load");try{const [saved,banners,rows]=await Promise.all([listAdminHomeSections(),listAdminBanners(),listAdminProducts()]);setSections(keys.map((key,index)=>{const found=saved.find(x=>x.section_key===key);return found?{...found,active:placeholders.includes(key)?false:found.active}:{id:`new-${key}`,section_key:key,...defaults[key],display_order:(index+1)*10,created_at:"",updated_at:""};}));setBanner(banners[0]??emptyBanner);setProducts(rows.filter(x=>x.active));}catch{setMessage({page:"Erro ao carregar a configuração."});}finally{setBusy(null);}};
  useEffect(()=>{void load()},[]);
  const get=(key:Key)=>sections.find(x=>x.section_key===key)!;
  const patch=(key:Key,value:any)=>setSections(current=>current.map(x=>x.section_key===key?{...x,...value}:x));
  const content=(key:Key,value:any)=>patch(key,{content:{...get(key).content,...value}});
  const save=async(key:Key)=>{setBusy(key);try{const saved=await saveAdminHomeSection({...get(key),active:placeholders.includes(key)?false:get(key).active});patch(key,saved);setMessage(x=>({...x,[key]:"Salvo com sucesso."}));}catch{setMessage(x=>({...x,[key]:"Erro ao salvar."}));}finally{setBusy(null);}};
  const move=async(key:Key,direction:number)=>{const ordered=[...sections].sort((a,b)=>a.display_order-b.display_order),from=ordered.findIndex(x=>x.section_key===key),to=from+direction;if(to<0||to>=ordered.length)return;[ordered[from],ordered[to]]=[ordered[to],ordered[from]];const next=ordered.map((x,i)=>({...x,display_order:(i+1)*10}));setSections(next);setBusy("order");try{await Promise.all(next.map(x=>saveAdminHomeSection({...x,active:placeholders.includes(x.section_key as Key)?false:x.active})));setMessage(x=>({...x,order:"Ordem atualizada."}));}catch{await load();setMessage(x=>({...x,order:"Erro ao atualizar a ordem."}));}finally{setBusy(null);}};
  const common=(key:Key)=>{const s=get(key),placeholder=placeholders.includes(key);return <><div className="grid gap-4 md:grid-cols-2"><label>Título<input className={cls} value={s.title??""} onChange={e=>patch(key,{title:e.target.value})}/></label><label>Subtítulo<input className={cls} value={s.subtitle??""} onChange={e=>patch(key,{subtitle:e.target.value})}/></label></div><div className="flex flex-wrap items-center gap-4"><label>Ordem<input className="ml-2 w-24 rounded border px-3 py-2" type="number" value={s.display_order} onChange={e=>patch(key,{display_order:Number(e.target.value)})}/></label><label className="flex gap-2"><input type="checkbox" disabled={placeholder} checked={!placeholder&&s.active} onChange={e=>patch(key,{active:e.target.checked})}/>Ativa</label><button type="button" className="rounded border px-3 py-2" onClick={()=>void move(key,-1)}>Subir</button><button type="button" className="rounded border px-3 py-2" onClick={()=>void move(key,1)}>Descer</button></div></>};
  const shell=(key:Key,body?:ReactNode)=><section className="space-y-5 rounded-xl border bg-white p-6 shadow-sm"><div><h2 className="text-xl font-semibold">{labels[key]}</h2>{placeholders.includes(key)&&<p className="text-sm text-amber-700">Placeholder desativado nesta etapa.</p>}</div>{common(key)}{body}{message[key]&&<p className={message[key].startsWith("Erro")?"text-sm text-red-700":"text-sm text-green-700"}>{message[key]}</p>}<button type="button" disabled={busy===key} className="rounded bg-orange-500 px-4 py-2 font-semibold text-white" onClick={()=>void save(key)}>{busy===key?"Salvando...":"Salvar seção"}</button></section>;
  const itemEditor=(key:"destinations"|"benefits"|"testimonials",fields:[string,string,boolean?][])=>{const rows=Array.isArray(get(key).content?.items)?get(key).content.items:[];const update=(next:any[])=>content(key,{items:next});return <><div className="space-y-4">{rows.map((row:any,index:number)=><div className="grid gap-3 rounded border p-4 md:grid-cols-2" key={index}>{fields.map(([name,label,area])=><label className={area?"md:col-span-2":""} key={name}>{label}{area?<textarea className={`${cls} min-h-24`} value={row[name]??""} onChange={e=>{const next=[...rows];next[index]={...row,[name]:e.target.value};update(next)}}/>:<input className={cls} value={row[name]??(name==="description"?row.text??"":"")} onChange={e=>{const next=[...rows];next[index]={...row,[name]:e.target.value};update(next)}}/>}</label>)}<label>Ordem<input className={cls} type="number" value={row.order??index} onChange={e=>{const next=[...rows];next[index]={...row,order:Number(e.target.value)};update(next)}}/></label><label className="flex items-center gap-2"><input type="checkbox" checked={row.active!==false} onChange={e=>{const next=[...rows];next[index]={...row,active:e.target.checked};update(next)}}/>Ativo</label><button type="button" className="text-left text-red-600" onClick={()=>update(rows.filter((_:any,i:number)=>i!==index))}>Remover</button></div>)}</div><button type="button" className="rounded border px-4 py-2" onClick={()=>update([...rows,{order:rows.length,active:true}])}>Adicionar item</button></>};
  const saveBanner=async(e:FormEvent)=>{e.preventDefault();setBusy("banner");try{setBanner(await saveAdminBanner(banner));setMessage(x=>({...x,banner:"Banner salvo com sucesso."}));}catch{setMessage(x=>({...x,banner:"Erro ao salvar o banner."}));}finally{setBusy(null)}};
  if(busy==="load"||!sections.length)return <p>Carregando configurações...</p>;
  const featured=get("featured_products"),promo=get("promotional_banner"),ids=Array.isArray(featured.content?.product_ids)?featured.content.product_ids:[];
  return <div className="space-y-6">{message.page&&<p className="text-red-700">{message.page}</p>}{message.order&&<p>{message.order}</p>}
    <form onSubmit={saveBanner} className="space-y-5 rounded-xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-semibold">Banner principal</h2><div className="grid gap-4 md:grid-cols-2">{[["title","Título"],["subtitle","Subtítulo"],["image_url","URL da imagem"],["mobile_image_url","URL da imagem mobile"],["button_text","Texto do botão"],["button_url","URL do botão"]].map(([name,label])=><label key={name}>{label}<input className={cls} value={(banner[name as keyof HomeBanner] as string)??""} onChange={e=>setBanner({...banner,[name]:e.target.value})}/></label>)}</div><div className="flex flex-wrap gap-4"><label>Overlay<input className="ml-2 w-24 rounded border px-3 py-2" min="0" max="1" step=".05" type="number" value={banner.overlay_strength??.35} onChange={e=>setBanner({...banner,overlay_strength:Number(e.target.value)})}/></label><label>Ordem<input className="ml-2 w-24 rounded border px-3 py-2" type="number" value={banner.display_order??0} onChange={e=>setBanner({...banner,display_order:Number(e.target.value)})}/></label><label className="flex gap-2"><input type="checkbox" checked={banner.active??true} onChange={e=>setBanner({...banner,active:e.target.checked})}/>Ativo</label></div>{message.banner&&<p>{message.banner}</p>}<button className="rounded bg-orange-500 px-4 py-2 font-semibold text-white">{busy==="banner"?"Salvando...":"Salvar banner"}</button></form>
    {shell("featured_products",<><label>Quantidade<input className={cls} min="1" max="12" type="number" value={featured.content?.limit??6} onChange={e=>content("featured_products",{limit:Number(e.target.value)})}/></label><div className="grid gap-2 md:grid-cols-2">{products.map(product=><label className="flex gap-2 rounded border p-3" key={product.id}><input type="checkbox" checked={ids.includes(product.id)} onChange={e=>content("featured_products",{product_ids:e.target.checked?[...ids,product.id]:ids.filter((id:string)=>id!==product.id)})}/>{product.title}</label>)}</div></>)}
    {shell("destinations",itemEditor("destinations",[["title","Destino"],["subtitle","Localização"],["image","URL da imagem"],["url","URL do link"]]))}
    {shell("benefits",itemEditor("benefits",[["title","Título"],["description","Descrição"],["icon","Ícone"]]))}
    {shell("testimonials",<><p className="text-sm text-gray-600">Cadastre somente depoimentos reais e autorizados.</p>{itemEditor("testimonials",[["name","Nome"],["city","Cidade"],["photo","URL da foto (opcional)"],["text","Texto",true]])}</>)}
    {shell("promotional_banner",<div className="grid gap-4 md:grid-cols-2"><label className="md:col-span-2">Texto<textarea className={`${cls} min-h-24`} value={promo.content?.text??""} onChange={e=>content("promotional_banner",{text:e.target.value})}/></label><label>Texto do botão<input className={cls} value={promo.content?.button_text??""} onChange={e=>content("promotional_banner",{button_text:e.target.value})}/></label><label>URL do botão<input className={cls} value={promo.content?.button_url??""} onChange={e=>content("promotional_banner",{button_url:e.target.value})}/></label></div>)}
    {shell("latest_blog_posts")}{shell("newsletter")}
  </div>;
};
export default HomeEditor;
